algoritmo "retornando variáveis na tela"
// Função :
// Autor :
// Data : 17/08/2021
// Seção de Declarações 
var
nome, endereco:caracter
idade:inteiro
inicio
// Seção de Comandos
escreva("Digite o seu nome: ")
leia(nome)
escreva("Digite a sua idade: ")
leia(idade)
escreva("Digite o seu endereço: ")
leia(endereco)
escreval()
escreval("Seu nome: ", nome)
escreval("Sua idade: ", idade)
escreval("Seu endereço: ", endereco)
fimalgoritmo